#   ██████╗ ██╗  *██╗██████╗ ██████╗ ██╗   ██╗ * * * * =
#  ██╔════╝ ██║===██║██╔══██╗██╔══██╗╚██╗ ██╔╝* *  ===     *
#  ██║  ███╗██║==*██║██████╔╝██████╔╝ ╚████╔╝ * * *  *  * * ==
#  ██║   ██║██║ =*██║██╔═══╝ ██╔═══╝ * ╚██╔╝* * Version [1.0.0] * *==
#  ╚██████╔╝╚██████╔╝██║* *  ██║ * *=  *██║* =  *   ==  *
#   ╚═════╝  ╚═════╝ ╚═╝     ╚═╝        ╚═╝    *    *  *===
#--------------------------------------------------------------------------------------
# Provide the unique token for your bot from the discord developer portal.
# Make sure you have activated privileged intents & allowed scopes applications.commands and bot.
token: 'NzgwNTc4MTU4NTk2NDU2NDc4.Gn9bdA.VRO7jloqcXNzeW-nh6EkJQSQbm3C1LF85OMdNI'
#
# Use your guild's id here!
guild: 570063954118836245
#
# The estimated size of your discord server. Used to determine member caching responsibility.
estimated-size: 200
#
# The activity shown for the bot.
activity:
  style: WATCHING
  info: 'Aqua Teen Hunger Force'

channels:
  commands:
    #
    #
    id: 671895225924321281
#--------------------------------------------------------------------------------------